name: xy_music_mobile
description: 全网音乐播放器

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #路由
  fluro: ^2.0.3
  #全局状态管理器
  provider: ^5.0.0
  #组件状态管理器
  scoped_model: ^1.1.0
  #图片缓存
  cached_network_image: ^3.0.0
  #网络请求
  dio: ^4.0.0
  #Sql数据库
  sqflite: ^2.0.0+3
  #EventBus 消息总线
  event_bus: ^2.0.0
  #权限检测器
  permission_handler: ^7.2.0
  #持久化存储
  shared_preferences: ^2.0.5
  #设备存储目录获取
  path_provider: ^2.0.1
  #Toast
  fluttertoast: ^8.0.7
  #Svg
  flutter_svg: ^0.22.0
  #ListView 的item侧滑菜单组件
  flutter_slidable: ^0.6.0
  #时间格式化工具与国际化插件
  intl: ^0.17.0
  #图片放大预览
  photo_view: ^0.11.1
  #监听网络状态
  connectivity: ^3.0.4
  #保存到图片到本地
  image_gallery_saver: '^1.6.9'
  #获取版本号
  get_version: ^0.2.2
  #NoSql数据库
  hive: ^2.0.4
  #ListView滚动到列表中指定item
  scrollable_positioned_list: ^0.1.10
  #音乐播放组件
  audioplayers: ^0.19.0
  #后台控制中心 音乐播放服务
  audio_service: ^0.17.0
  url_launcher: ^6.0.4
  overlay: ^0.0.1
  #日志打印
  logger: ^1.0.0
  rxdart: ^0.27.1
  #粘性悬浮组件
  flutter_sticky_header: ^0.6.0
  # encrypt: ^5.0.0
  #Json 序列化
  # json_annotation: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  #NoSql数据库
  hive_generator: ^1.1.0
  #Json 序列化
  # json_serializable: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/tmp/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
